In [1]:
import pandas as pd

In [2]:
bluebikes_df = pd.read_csv('Final BlueBikes Data.csv')

In [3]:
bluebikes_df

,bike_id,start_time,end_time,start_station_id,end_station_id,user_type,user_birth_year,ride_year,ride_month,journey_time,start_jrny_name,start_jrny_latitude,start_jrny_longitude,start_jrny_district,start_jrny_docks,end_jrny_name,end_jrny_latitude,end_jrny_longitude,end_jrny_district,end_jrny_docks
0,1380,2016-11-01 00:00:35,2016-11-01 00:03:52,95,78,Subscriber,1983.0,2016,11,3.28,Cambridge St - at Columbia St / Webster Ave,42.372969,-71.094445,Cambridge,15.0,Union Square - Somerville,42.379674,-71.093913,Somerville,19.0
1,866,2016-11-01 00:01:23,2016-11-01 00:05:06,23,190,Subscriber,1980.0,2016,11,3.72,Boston City Hall - 28 State St,42.358920,-71.057629,Boston,21.0,Nashua Street at Red Auerbach Way,42.365673,-71.064263,Boston,37.0
2,35,2016-11-01 00:04:19,2016-11-01 00:12:22,178,184,Subscriber,1990.0,2016,11,8.05,MIT Pacific St at Purrington St,42.359573,-71.101295,Cambridge,19.0,Sidney Research Campus/Erie Street at Waverly,42.357753,-71.103934,Cambridge,19.0
3,1917,2016-11-01 00:05:31,2016-11-01 00:07:53,25,21,Customer,NaN,2016,11,2.37,South End Library - Tremont St at W Newton St,42.341332,-71.076847,Boston,15.0,Prudential Center - 101 Huntington Ave,42.346520,-71.080658,Boston,18.0
4,603,2016-11-01 00:05:59,2016-11-01 00:08:34,76,139,Subscriber,1990.0,2016,11,2.58,Central Sq Post Office / Cambridge City Hall a...,42.366426,-71.105495,Cambridge,17.0,Dana Park,42.361780,-71.108100,Cambridge,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6834925,420,2016-05-31 22:18:44,2016-05-31 22:27:15,67,33,Subscriber,1997.0,2016,5,8.52,MIT at Mass Ave / Amherst St,42.358100,-71.093198,Cambridge,27.0,Kenmore Square,42.348706,-71.097009,Boston,27.0
6834926,650,2016-05-31 22:21:19,2016-05-31 22:30:33,61,13,Subscriber,1990.0,2016,5,9.23,Boylston St at Fairfield St,42.348762,-71.082383,Boston,19.0,Boston Medical Center - E Concord St at Harris...,42.336399,-71.073067,Boston,19.0
6834927,1474,2016-05-31 22:25:51,2016-05-31 22:44:38,79,60,Customer,NaN,2016,5,18.78,Beacon St at Washington / Kirkland,42.378420,-71.105668,Somerville,19.0,Charles Circle - Charles St at Cambridge St,42.360793,-71.071190,Boston,19.0
6834928,391,2016-05-31 22:26:39,2016-05-31 22:28:28,151,192,Subscriber,1981.0,2016,5,1.82,Surface Rd at India St,42.358155,-71.052163,Boston,19.0,Purchase St at Pearl St,42.354659,-71.053181,Boston,19.0
6834929,947,2016-05-31 22:27:09,2016-05-31 22:31:30,50,134,Customer,NaN,2016,5,4.35,Boylston St at Berkeley St,42.351142,-71.073292,Boston,15.0,NaN,NaN,NaN,NaN,NaN

In [10]:
start_journey_df = bluebikes_df.groupby(['start_jrny_name'])['bike_id'].count()

In [11]:
start_journey_df = start_journey_df.reset_index(name="Total Starts")

                               start_jrny_name  Total Starts
0                             175 N Harvard St         34436
1                                191 Beacon St          6074
2                                   30 Dane St         10372
3    359 Broadway - Broadway at Fayette Street         46189
4                             699 Mt Auburn St          4392
..                                         ...           ...
323                              West End Park         30633
324               Western Ave at Richardson St           856
325                  Whittier St Health Center           202
326               Williams St at Washington St          2624
327                              Wilson Square         14303

[328 rows x 2 columns]

In [21]:
start_journey_df = start_journey_df.rename(columns={'start_jrny_name': 'Station name'})

In [22]:
start_journey_df

                                  Station name  Total Starts
0                             175 N Harvard St         34436
1                                191 Beacon St          6074
2                                   30 Dane St         10372
3    359 Broadway - Broadway at Fayette Street         46189
4                             699 Mt Auburn St          4392
..                                         ...           ...
323                              West End Park         30633
324               Western Ave at Richardson St           856
325                  Whittier St Health Center           202
326               Williams St at Washington St          2624
327                              Wilson Square         14303

[328 rows x 2 columns]

In [14]:
end_journey_df = bluebikes_df.groupby(['end_jrny_name'])['bike_id'].count()

In [15]:
end_journey_df = end_journey_df.reset_index(name="Total Ends")

In [23]:
end_journey_df = end_journey_df.rename(columns={'end_jrny_name': 'Station name'})

In [24]:
end_journey_df

                                  Station name  Total Ends
0                             175 N Harvard St       34747
1                                191 Beacon St        5916
2                                   30 Dane St       10496
3    359 Broadway - Broadway at Fayette Street       37588
4                             699 Mt Auburn St        4594
..                                         ...         ...
323                              West End Park       29677
324               Western Ave at Richardson St         907
325                  Whittier St Health Center         229
326               Williams St at Washington St        2836
327                              Wilson Square       13133

[328 rows x 2 columns]

In [25]:
combined_journey_df = start_journey_df.merge(
end_journey_df[["Station name", "Total Ends"]],
on= ["Station name"], 
how="outer")

In [26]:
combined_journey_df

                                  Station name  Total Starts  Total Ends
0                             175 N Harvard St         34436       34747
1                                191 Beacon St          6074        5916
2                                   30 Dane St         10372       10496
3    359 Broadway - Broadway at Fayette Street         46189       37588
4                             699 Mt Auburn St          4392        4594
..                                         ...           ...         ...
323                              West End Park         30633       29677
324               Western Ave at Richardson St           856         907
325                  Whittier St Health Center           202         229
326               Williams St at Washington St          2624        2836
327                              Wilson Square         14303       13133

[328 rows x 3 columns]

In [27]:
combined_journey_df.to_csv('Station Start_End Data.csv')