<h1 style="text-align:center; font-size: 4em;">Bluebikes Data Preparation and Analysis (2016 - 2019)</h1>

In [1]:
import pandas as pd

In [2]:
weather_summary_df = pd.read_csv('Weather_Summary_2016-2019.csv')

In [3]:
weather_summary_df

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD,TMAX,TMIN
0,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,01/01/2016,0.0,0.0,NaN,5.0,0.6
1,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,02/01/2016,0.0,0.0,NaN,4.4,-0.5
2,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,03/01/2016,0.0,0.0,NaN,6.7,-0.5
3,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,04/01/2016,0.0,0.0,NaN,2.2,-9.9
4,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,05/01/2016,0.0,0.0,NaN,-3.2,-13.2
...,...,...,...,...,...,...,...,...,...,...,...
8752,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,27/12/2019,0.0,NaN,NaN,11.7,1.1
8753,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,28/12/2019,0.0,NaN,NaN,11.1,-2.1
8754,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,29/12/2019,2.5,NaN,NaN,8.3,-4.9
8755,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,30/12/2019,32.3,NaN,NaN,5.0,2.8
8756,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,31/12/2019,5.3,NaN,NaN,7.2,3.3

In [4]:
weather_summary_df.shape

(8757, 11)

In [5]:
weather_summary_df.dtypes

STATION       object
NAME          object
LATITUDE     float64
LONGITUDE    float64
ELEVATION    float64
DATE          object
PRCP         float64
SNOW         float64
SNWD         float64
TMAX         float64
TMIN         float64
dtype: object

In [6]:
weather_summary_df["DATE"] = pd.to_datetime(weather_summary_df["DATE"],format="%d/%m/%Y")

In [7]:
weather_summary_df.dtypes

STATION              object
NAME                 object
LATITUDE            float64
LONGITUDE           float64
ELEVATION           float64
DATE         datetime64[ns]
PRCP                float64
SNOW                float64
SNWD                float64
TMAX                float64
TMIN                float64
dtype: object

In [8]:
(weather_summary_df.isnull().sum())

STATION         0
NAME            0
LATITUDE        0
LONGITUDE       0
ELEVATION       0
DATE            0
PRCP           69
SNOW         2922
SNWD         4383
TMAX           22
TMIN           23
dtype: int64

In [9]:
print(weather_summary_df["DATE"].min())

2016-01-01 00:00:00

In [10]:
print(weather_summary_df["DATE"].max())

2019-12-31 00:00:00

In [11]:
print(weather_summary_df['STATION'].unique())

['USW00014739' 'USC00193890' 'USW00014753' 'USC00196783' 'USW00014702'
 'USW00054704']

In [12]:
print(weather_summary_df['NAME'].unique())

['BOSTON LOGAN INTERNATIONAL AIRPORT, MA US' 'JAMAICA PLAIN, MA US'
 'BLUE HILL LCD, MA US' 'READING, MA US' 'BEDFORD HANSCOM FIELD, MA US'
 'NORWOOD MEMORIAL AIRPORT, MA US']

In [13]:
weather_mapping_df = pd.read_csv('NOAA_Station_mapping.csv')

In [14]:
weather_mapping_df

,district,station_id,station_name,station_latitude,station_longitude
0,Boston,USW00014739,BOSTON LOGAN INTERNATIONAL AIRPORT,42.36057,-71.00975
1,Brookline,USC00193890,JAMAICA PLAIN,42.30310,-71.12420
2,Cambridge,USW00014753,BLUE HILL,42.21220,-71.11360
3,Everett,USC00196783,READING,42.52400,-71.12490
4,Somerville,USW00014702,BEDFORD HANSCOM FIELD,42.46810,-71.29470
5,Watertown,USW00054704,NORWOOD MEMORIAL AIRPORT,42.19110,-71.17330

In [15]:
weather_summary_df = weather_summary_df.merge(
weather_mapping_df[["station_id", "district"]],
left_on="STATION",
right_on="station_id",
how="left"
).drop(columns="station_id")

In [16]:
weather_summary_df

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,SNOW,SNWD,TMAX,TMIN,district
0,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,2016-01-01,0.0,0.0,NaN,5.0,0.6,Boston
1,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,2016-01-02,0.0,0.0,NaN,4.4,-0.5,Boston
2,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,2016-01-03,0.0,0.0,NaN,6.7,-0.5,Boston
3,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,2016-01-04,0.0,0.0,NaN,2.2,-9.9,Boston
4,USW00014739,"BOSTON LOGAN INTERNATIONAL AIRPORT, MA US",42.36057,-71.00975,3.2,2016-01-05,0.0,0.0,NaN,-3.2,-13.2,Boston
...,...,...,...,...,...,...,...,...,...,...,...,...
8752,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,2019-12-27,0.0,NaN,NaN,11.7,1.1,Watertown
8753,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,2019-12-28,0.0,NaN,NaN,11.1,-2.1,Watertown
8754,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,2019-12-29,2.5,NaN,NaN,8.3,-4.9,Watertown
8755,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,2019-12-30,32.3,NaN,NaN,5.0,2.8,Watertown
8756,USW00054704,"NORWOOD MEMORIAL AIRPORT, MA US",42.19123,-71.17326,13.0,2019-12-31,5.3,NaN,NaN,7.2,3.3,Watertown

In [17]:
bluebikes_df = pd.read_csv('Final BlueBikes Data.csv')

In [18]:
bluebikes_df

,bike_id,start_time,end_time,start_station_id,end_station_id,user_type,user_birth_year,ride_year,ride_month,journey_time,start_jrny_name,start_jrny_latitude,start_jrny_longitude,start_jrny_district,start_jrny_docks,end_jrny_name,end_jrny_latitude,end_jrny_longitude,end_jrny_district,end_jrny_docks
0,1380,2016-11-01 00:00:35,2016-11-01 00:03:52,95,78,Subscriber,1983.0,2016,11,3.28,Cambridge St - at Columbia St / Webster Ave,42.372969,-71.094445,Cambridge,15.0,Union Square - Somerville,42.379674,-71.093913,Somerville,19.0
1,866,2016-11-01 00:01:23,2016-11-01 00:05:06,23,190,Subscriber,1980.0,2016,11,3.72,Boston City Hall - 28 State St,42.358920,-71.057629,Boston,21.0,Nashua Street at Red Auerbach Way,42.365673,-71.064263,Boston,37.0
2,35,2016-11-01 00:04:19,2016-11-01 00:12:22,178,184,Subscriber,1990.0,2016,11,8.05,MIT Pacific St at Purrington St,42.359573,-71.101295,Cambridge,19.0,Sidney Research Campus/Erie Street at Waverly,42.357753,-71.103934,Cambridge,19.0
3,1917,2016-11-01 00:05:31,2016-11-01 00:07:53,25,21,Customer,NaN,2016,11,2.37,South End Library - Tremont St at W Newton St,42.341332,-71.076847,Boston,15.0,Prudential Center - 101 Huntington Ave,42.346520,-71.080658,Boston,18.0
4,603,2016-11-01 00:05:59,2016-11-01 00:08:34,76,139,Subscriber,1990.0,2016,11,2.58,Central Sq Post Office / Cambridge City Hall a...,42.366426,-71.105495,Cambridge,17.0,Dana Park,42.361780,-71.108100,Cambridge,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6834925,420,2016-05-31 22:18:44,2016-05-31 22:27:15,67,33,Subscriber,1997.0,2016,5,8.52,MIT at Mass Ave / Amherst St,42.358100,-71.093198,Cambridge,27.0,Kenmore Square,42.348706,-71.097009,Boston,27.0
6834926,650,2016-05-31 22:21:19,2016-05-31 22:30:33,61,13,Subscriber,1990.0,2016,5,9.23,Boylston St at Fairfield St,42.348762,-71.082383,Boston,19.0,Boston Medical Center - E Concord St at Harris...,42.336399,-71.073067,Boston,19.0
6834927,1474,2016-05-31 22:25:51,2016-05-31 22:44:38,79,60,Customer,NaN,2016,5,18.78,Beacon St at Washington / Kirkland,42.378420,-71.105668,Somerville,19.0,Charles Circle - Charles St at Cambridge St,42.360793,-71.071190,Boston,19.0
6834928,391,2016-05-31 22:26:39,2016-05-31 22:28:28,151,192,Subscriber,1981.0,2016,5,1.82,Surface Rd at India St,42.358155,-71.052163,Boston,19.0,Purchase St at Pearl St,42.354659,-71.053181,Boston,19.0
6834929,947,2016-05-31 22:27:09,2016-05-31 22:31:30,50,134,Customer,NaN,2016,5,4.35,Boylston St at Berkeley St,42.351142,-71.073292,Boston,15.0,NaN,NaN,NaN,NaN,NaN

In [19]:
bluebikes_df.shape

(6834930, 20)

In [20]:
(bluebikes_df.isnull().sum())

bike_id                      0
start_time                   0
end_time                     0
start_station_id             0
end_station_id               0
user_type                    0
user_birth_year         448150
ride_year                    0
ride_month                   0
journey_time                 0
start_jrny_name         131385
start_jrny_latitude     131385
start_jrny_longitude    131385
start_jrny_district     131385
start_jrny_docks        131385
end_jrny_name           129548
end_jrny_latitude       129548
end_jrny_longitude      129548
end_jrny_district       129548
end_jrny_docks          129548
dtype: int64

In [21]:
bluebikes_df.dtypes

bike_id                   int64
start_time               object
end_time                 object
start_station_id          int64
end_station_id            int64
user_type                object
user_birth_year         float64
ride_year                 int64
ride_month                int64
journey_time            float64
start_jrny_name          object
start_jrny_latitude     float64
start_jrny_longitude    float64
start_jrny_district      object
start_jrny_docks        float64
end_jrny_name            object
end_jrny_latitude       float64
end_jrny_longitude      float64
end_jrny_district        object
end_jrny_docks          float64
dtype: object

In [ ]:
bluebikes_df["start_time"] = pd.to_datetime(bluebikes_df["start_time"],format="mixed")

In [23]:
bluebikes_df.dtypes

bike_id                          int64
start_time              datetime64[ns]
end_time                        object
start_station_id                 int64
end_station_id                   int64
user_type                       object
user_birth_year                float64
ride_year                        int64
ride_month                       int64
journey_time                   float64
start_jrny_name                 object
start_jrny_latitude            float64
start_jrny_longitude           float64
start_jrny_district             object
start_jrny_docks               float64
end_jrny_name                   object
end_jrny_latitude              float64
end_jrny_longitude             float64
end_jrny_district               object
end_jrny_docks                 float64
dtype: object

In [ ]:
bluebikes_df["DATE"] = pd.to_datetime(bluebikes_df["start_time"]).dt.normalize()

In [ ]:
grouped_bluebikes_df = bluebikes_df.groupby(["DATE", "start_jrny_district"]).size().reset_index(name="Total Journeys")

In [26]:
grouped_bluebikes_df

           DATE start_jrny_district  Total Journeys
0    2016-01-01              Boston              21
1    2016-01-01           Cambridge             210
2    2016-01-02           Cambridge             211
3    2016-01-03           Cambridge             232
4    2016-01-04           Cambridge             275
...         ...                 ...             ...
5476 2019-12-31              Boston            1016
5477 2019-12-31           Brookline              40
5478 2019-12-31           Cambridge             628
5479 2019-12-31             Everett               4
5480 2019-12-31          Somerville             125

[5481 rows x 3 columns]

In [27]:
final_weather_df = grouped_bluebikes_df.merge(
weather_summary_df[["DATE", "district", "PRCP", "SNOW", "SNWD", "TMAX", "TMIN"]],
left_on= ["DATE", "start_jrny_district"], 
right_on=["DATE", "district"],
how="left"
)

In [28]:
final_weather_df

,DATE,start_jrny_district,Total Journeys,district,PRCP,SNOW,SNWD,TMAX,TMIN
0,2016-01-01,Boston,21,Boston,0.0,0.0,NaN,5.0,0.6
1,2016-01-01,Cambridge,210,Cambridge,0.0,0.0,0.0,2.8,-1.7
2,2016-01-02,Cambridge,211,Cambridge,0.0,0.0,0.0,2.8,-2.8
3,2016-01-03,Cambridge,232,Cambridge,0.0,0.0,0.0,5.0,-2.8
4,2016-01-04,Cambridge,275,Cambridge,0.0,5.0,0.0,-1.1,-12.2
...,...,...,...,...,...,...,...,...,...
5476,2019-12-31,Boston,1016,Boston,6.9,0.0,NaN,6.7,2.8
5477,2019-12-31,Brookline,40,Brookline,35.1,0.0,0.0,5.0,1.1
5478,2019-12-31,Cambridge,628,Cambridge,8.4,0.0,0.0,4.4,0.0
5479,2019-12-31,Everett,4,NaN,NaN,NaN,NaN,NaN,NaN
5480,2019-12-31,Somerville,125,Somerville,4.3,NaN,NaN,3.9,1.1

In [29]:
final_weather_df.isnull().sum()

DATE                      0
start_jrny_district       0
Total Journeys            0
district                  7
PRCP                     32
SNOW                   1295
SNWD                   2649
TMAX                     14
TMIN                     14
dtype: int64

In [30]:
final_weather_df = final_weather_df.rename(columns={
    "PRCP": "Rainfall (mm)",
    "SNOW": "Snowfall (mm)",
    "SNWD": "Snow on ground (mm)",
    "TMAX": "Max Temp (°C)",
    "TMIN": "Min Temp (°C)"
})

In [31]:
final_weather_df

,DATE,start_jrny_district,Total Journeys,district,Rainfall (mm),Snowfall (mm),Snow on ground (mm),Max Temp (°C),Min Temp (°C)
0,2016-01-01,Boston,21,Boston,0.0,0.0,NaN,5.0,0.6
1,2016-01-01,Cambridge,210,Cambridge,0.0,0.0,0.0,2.8,-1.7
2,2016-01-02,Cambridge,211,Cambridge,0.0,0.0,0.0,2.8,-2.8
3,2016-01-03,Cambridge,232,Cambridge,0.0,0.0,0.0,5.0,-2.8
4,2016-01-04,Cambridge,275,Cambridge,0.0,5.0,0.0,-1.1,-12.2
...,...,...,...,...,...,...,...,...,...
5476,2019-12-31,Boston,1016,Boston,6.9,0.0,NaN,6.7,2.8
5477,2019-12-31,Brookline,40,Brookline,35.1,0.0,0.0,5.0,1.1
5478,2019-12-31,Cambridge,628,Cambridge,8.4,0.0,0.0,4.4,0.0
5479,2019-12-31,Everett,4,NaN,NaN,NaN,NaN,NaN,NaN
5480,2019-12-31,Somerville,125,Somerville,4.3,NaN,NaN,3.9,1.1

In [32]:
final_weather_df.drop(columns="district")

,DATE,start_jrny_district,Total Journeys,Rainfall (mm),Snowfall (mm),Snow on ground (mm),Max Temp (°C),Min Temp (°C)
0,2016-01-01,Boston,21,0.0,0.0,NaN,5.0,0.6
1,2016-01-01,Cambridge,210,0.0,0.0,0.0,2.8,-1.7
2,2016-01-02,Cambridge,211,0.0,0.0,0.0,2.8,-2.8
3,2016-01-03,Cambridge,232,0.0,0.0,0.0,5.0,-2.8
4,2016-01-04,Cambridge,275,0.0,5.0,0.0,-1.1,-12.2
...,...,...,...,...,...,...,...,...
5476,2019-12-31,Boston,1016,6.9,0.0,NaN,6.7,2.8
5477,2019-12-31,Brookline,40,35.1,0.0,0.0,5.0,1.1
5478,2019-12-31,Cambridge,628,8.4,0.0,0.0,4.4,0.0
5479,2019-12-31,Everett,4,NaN,NaN,NaN,NaN,NaN
5480,2019-12-31,Somerville,125,4.3,NaN,NaN,3.9,1.1

In [33]:
len(grouped_bluebikes_df)

5481

In [34]:
len(final_weather_df)

5481

In [ ]:
final_weather_df.duplicated(subset=["DATE", "start_jrny_district"]).sum()

np.int64(0)

In [36]:
x = grouped_bluebikes_df["Total Journeys"].sum()
y = final_weather_df["Total Journeys"].sum()

print(x-y)

0

In [37]:
final_weather_df.isna().sum()

DATE                      0
start_jrny_district       0
Total Journeys            0
district                  7
Rainfall (mm)            32
Snowfall (mm)          1295
Snow on ground (mm)    2649
Max Temp (°C)            14
Min Temp (°C)            14
dtype: int64

In [38]:
final_weather_df["start_jrny_district"].value_counts()

start_jrny_district
Cambridge     1459
Boston        1354
Somerville    1286
Brookline     1181
Everett        201
Name: count, dtype: int64

In [39]:
print(final_weather_df["DATE"].min(),
final_weather_df["DATE"].max())

2016-01-01 00:00:00 2019-12-31 00:00:00

In [40]:
final_weather_df[
    final_weather_df["Max Temp (°C)"] <
    final_weather_df["Min Temp (°C)"]]

Empty DataFrame
Columns: [DATE, start_jrny_district, Total Journeys, district, Rainfall (mm), Snowfall (mm), Snow on ground (mm), Max Temp (°C), Min Temp (°C)]
Index: []

In [41]:
final_weather_df.sample(10)

,DATE,start_jrny_district,Total Journeys,district,Rainfall (mm),Snowfall (mm),Snow on ground (mm),Max Temp (°C),Min Temp (°C)
3944,2019-02-01,Boston,1135,Boston,0.0,0.0,NaN,-4.9,-12.1
2155,2017-11-07,Somerville,183,Somerville,2.5,NaN,NaN,8.9,1.7
302,2016-05-19,Cambridge,1571,Cambridge,6.6,0.0,0.0,18.9,9.4
1714,2017-07-20,Cambridge,2053,Cambridge,0.0,0.0,0.0,32.2,21.1
2283,2017-12-09,Somerville,31,Somerville,1.3,NaN,NaN,1.1,-1.0
5310,2019-11-27,Somerville,393,Somerville,8.4,NaN,NaN,11.7,-2.1
3739,2018-12-10,Somerville,146,Somerville,0.0,NaN,NaN,3.9,-9.3
3050,2018-06-21,Cambridge,2771,Cambridge,0.0,0.0,0.0,27.2,16.7
1634,2017-06-30,Cambridge,1880,Cambridge,2.8,0.0,0.0,27.8,18.3
203,2016-04-23,Somerville,131,Somerville,1.8,NaN,NaN,18.9,7.2

In [42]:
final_weather_df.to_csv('Weather Enrichment Data.csv')